import fs from "node:fs";
import path from "node:path";
import os from "node:os";

import { DOCKERFILES_MD } from "./dockerfiles-reference.js";

export function generateSkillContent(): string {
  // Strip Claude-specific frontmatter, return just the body
  return generateClaudeSkill().replace(/^---[\s\S]*?---\n\n/, "");
}

export { generateCommandsReference };

function generateClaudeSkill(): string {
  return [
    "---",
    "name: managing-infrastructure",
    "description: Deploys and manages apps, servers, databases, domains, and environment variables on VPS providers (Hetzner, Vultr, DigitalOcean) using the Hoist CLI. Triggers when user mentions deploying, provisioning servers, creating databases, configuring domains, managing env vars, or checking infrastructure health.",
    "---",
    "",
    "# Hoist CLI",
    "",
    "Hoist is an **AI-native CLI** — built specifically for AI agents, not humans. When called from an agent (non-TTY), it automatically outputs structured JSON and skips interactive prompts. Just run commands directly — no flags needed.",
    "",
    "## How You Should Behave",
    "",
    "You are the user's infrastructure guide. Be thorough and transparent:",
    "",
    "- **Always explain what you're about to do before doing it.** Tell the user which commands you'll run, what resources will be created, and what the estimated cost is.",
    "- **Ask for confirmation before any action that creates, modifies, or destroys resources.** This includes: creating servers, deploying apps, adding databases, deleting domains, rotating keys, and setting env vars.",
    "- **Never assume — always ask.** If the user says \"deploy this\", ask which server, which service, which port. Don't pick defaults silently.",
    "- **Present options clearly.** When there are choices (region, server type, database version), list them with context (price, location, specs) so the user can make an informed decision.",
    "- **After every action, verify it worked.** Run `hoist status` or `hoist doctor` and report the result.",
    "- **If something fails, investigate before retrying.** Check logs with `hoist logs`, run `hoist doctor`, and explain the issue to the user.",
    "",
    "## Smart Defaults",
    "",
    "Hoist auto-detects and fills in sensible defaults when called from an agent:",
    "- Auto-selects the only app service if just one exists",
    "- Auto-resolves `--server` from the service config in hoist.json",
    "- Generates random server names if `--name` is omitted",
    "- Uses cheapest server type and first region as defaults",
    "- Template `--name` defaults to `--type` (e.g., `--type postgres` creates a service named `postgres`)",
    "",
    "**Even though defaults exist, always present the plan to the user and get confirmation before executing.**",
    "",
    "## When to Use",
    "",
    '- "Deploy this app" -> `hoist deploy`',
    '- "Create a server" -> `hoist server create`',
    '- "Set up Postgres" -> `hoist template create --type postgres`',
    '- "Add a domain" -> `hoist domain add example.com`',
    '- "What\'s running?" -> `hoist status`',
    '- "Check health" -> `hoist doctor`',
    "",
    "## When NOT to Use",
    "",
    "- **Provider setup** (`hoist provider add`) — always interactive, tell the user to run this themselves.",
    "- **General coding** — Hoist is for infrastructure only.",
    "",
    "---",
    "",
    "## Decision Tree",
    "",
    "```",
    "Is hoist installed? (which hoist)",
    "+-- NO -> Run: npm install -g hoist-cli",
    "+--",
    "Is hoist configured? (hoist provider list)",
    "+-- NO -> Are HOIST_*_API_KEY env vars set?",
    "    +-- YES -> Run: hoist init",
    "    +-- NO  -> Tell user to run: hoist init",
    "+-- YES -> Does hoist.json exist?",
    "    +-- NO -> Create hoist.json (ask user about project name and structure)",
    "    +-- YES -> What does the user want?",
    "        +-- New server     -> hoist server create",
    "        +-- Import server  -> hoist server import --ip <ip>",
    "        +-- Deploy app     -> hoist deploy",
    "        +-- Add database   -> hoist template create --type postgres",
    "        +-- Add domain     -> hoist domain add <domain>",
    "        +-- Set env vars   -> hoist env set <service> KEY=VAL",
    "        +-- Check status   -> hoist status",
    "        +-- Diagnose issue -> hoist doctor",
    "```",
    "",
    "---",
    "",
    "## Sensitive Operations — Human in the Loop",
    "",
    "| Command | Behavior |",
    "|---------|----------|",
    "| `hoist init` | If `HOIST_*_API_KEY` env vars are set, auto-configures. Otherwise prompts interactively — tell user to run this. |",
    "| `hoist provider add` | Always interactive — tell user to run this |",
    "| `hoist keys rotate` | Rotates SSH keys on all servers — always confirm with user first |",
    "| `hoist server destroy` | **Destroys a server permanently** — always confirm with user first |",
    "| `hoist template destroy` | **Destroys a database and its data** — always confirm with user first |",
    "| `hoist domain delete` | Removes domain + SSL — always confirm with user first |",
    "",
    "Environment variables: `HOIST_HETZNER_API_KEY`, `HOIST_VULTR_API_KEY`, `HOIST_DIGITALOCEAN_API_KEY`",
    "",
    "---",
    "",
    "## Commands",
    "",
    "For full command reference, see [COMMANDS.md](COMMANDS.md).",
    "",
    "**Providers:** `provider list`, `provider test`, `provider set-default`, `provider delete`",
    "",
    "**Servers:** `server create`, `server import`, `server list`, `server status <name>`, `server ssh <name>`, `server destroy <name>`",
    "",
    "**Deploy:** `deploy`, `deploy --service <name>`, `deploy --repo <url> --branch <branch>`, `rollback --service <name>`",
    "",
    "**Templates:** `template list`, `template info <name>`, `template create --type <type>`, `template services`, `template inspect <name>`, `template backup <name>`, `template destroy <name>`, `template stop/start/restart <name>`",
    "",
    "**Domains:** `domain add <domain>`, `domain list`, `domain delete <domain>`",
    "",
    "**Env vars:** `env set <service> KEY=VAL`, `env get <service> <key>`, `env list <service>`, `env delete <service> <key>`, `env import <service> <file>`, `env export <service>`",
    "",
    "**Monitoring:** `logs <service>`, `logs <service> --follow`, `status`, `doctor`",
    "",
    "**Other:** `keys show`, `keys rotate`, `config validate`, `skill export`, `--status` (quick overview)",
    "",
    "**Update CLI:** `npm install -g hoist-cli@latest`",
    "",
    "---",
    "",
    "## Project Config",
    "",
    "Read `hoist.json` in the project root for current project context (servers, services, domains).",
    "",
    "```json",
    "{",
    '  "project": "my-app",',
    '  "servers": { "prod": { "provider": "hetzner-1" } },',
    '  "services": {',
    '    "api": { "server": "prod", "type": "app", "source": ".", "port": 3000 },',
    '    "db": { "server": "prod", "type": "postgres", "version": "16" }',
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Deployment Procedure",
    "",
    "Walk the user through each step. Ask for confirmation before proceeding:",
    "",
    "1. **Server** — Which server? If none exist, ask the user: which provider, which region, which type, what name? Present available options with pricing.",
    "2. **Service** — App (needs Dockerfile + port) or database (pick type + version)? If no Dockerfile exists, generate one — see [DOCKERFILES.md](DOCKERFILES.md) for framework-specific examples. Show the user the Dockerfile before deploying.",
    "3. **Domain** (optional) — Ask if they want a custom domain. User must point DNS A record to server IP first. Explain this clearly.",
    "4. **Env vars** (optional) — Ask about DATABASE_URL, API keys, etc. If a database was just created, auto-suggest the connection URL.",
    "5. **Confirm** — Summarize everything that will happen (server, service, domain, env vars, estimated cost) and ask for a final go-ahead.",
    "",
    "---",
    "",
    "## After Deploying",
    "",
    "1. `hoist status` — verify deployment, report to user",
    "2. `hoist domain add <domain>` — custom domain + auto-SSL (if requested)",
    "3. `hoist doctor` — health check, report any issues",
    "",
    "## After Adding a Database",
    "",
    "1. `hoist template inspect <name>` — get credentials",
    "2. `hoist env set <app> DATABASE_URL=<url>` — inject into app",
    "3. Tell the user the database is ready and the app has been restarted with the new connection.",
    "",
    "## After an Error",
    "",
    "1. `hoist doctor` — diagnose",
    "2. `hoist logs <service> --lines 200` — check logs",
    "3. Explain the error to the user in plain language",
    "4. Suggest a fix. If rollback is needed, confirm with user first: `hoist rollback --service <name>`",
    "",
    "---",
    "",
    "## Error Reference",
    "",
    "| Error | Solution |",
    "|-------|----------|",
    '| "Run hoist init first" | If env vars are set, run `hoist init`. Otherwise tell user to run `hoist init`. |',
    '| "Provider not found" | Check `hoist provider list` for correct label |',
    '| "Server not found" | Check `hoist server list` |',
    '| "SSH connection failed" | Run `hoist doctor`, verify IP |',
    '| "No hoist.json found" | Create hoist.json in project root |',
    '| "references unknown server" | Server name in service must match servers section |',
    "",
    "---",
    "",
    "## Golden Rules",
    "",
    "1. **Explain first, act second.** Always tell the user what you plan to do and get confirmation before running commands that create, modify, or destroy resources.",
    "2. **Just run commands.** JSON output and confirmations are handled automatically — no flags needed.",
    "3. Parse stdout for JSON, check exit code (0 = ok, 1 = error).",
    "4. **Never handle API keys directly.** Use env vars (`HOIST_*_API_KEY`) or tell user to run setup commands.",
    "5. Run `hoist doctor` to diagnose any issue.",
    "6. After every action, verify it worked and report the result to the user.",
    "7. Server names in hoist.json must match what was used during creation.",
    "",
  ].join("\n");
}

function generateCommandsReference(): string {
  return [
    "# Hoist CLI — Full Command Reference",
    "",
    "Hoist is AI-native. All commands output structured JSON and skip interactive prompts automatically when called from an agent (non-TTY). No flags needed.",
    "",
    "## Init",
    "",
    "```bash",
    "hoist init                                # Auto-detects HOIST_*_API_KEY env vars, falls back to interactive",
    "```",
    "",
    "If any of these env vars are set, init auto-configures the provider (no prompts):",
    "- `HOIST_HETZNER_API_KEY`",
    "- `HOIST_VULTR_API_KEY`",
    "- `HOIST_DIGITALOCEAN_API_KEY`",
    "",
    "## Providers",
    "",
    "```bash",
    "hoist provider list",
    "hoist provider test [label]",
    "hoist provider set-default [label]",
    "hoist provider delete [label]",
    "```",
    "",
    "## Servers",
    "",
    "```bash",
    "hoist server create                                    # Auto: random name, cheapest type, first region",
    "hoist server create --name <n> --provider <p> --type <t> --region <r>  # Explicit",
    "hoist server import --ip <ip>                          # Auto: random name",
    "hoist server import --name <n> --ip <ip> [--user <user>]",
    "hoist server list [--provider <p>]",
    "hoist server status <name> [--provider <p>]",
    "hoist server ssh <name> [--provider <p>]",
    "hoist server destroy <name> [--provider <p>]",
    "```",
    "",
    "## Deploy & Rollback",
    "",
    "```bash",
    "hoist deploy                                           # Auto-selects service if only one app",
    "hoist deploy --service <name>                          # Deploy a specific service",
    "hoist deploy --repo <url> [--branch <branch>]          # From Git repo",
    "hoist rollback --service <name>                        # Server auto-resolved from hoist.json",
    "```",
    "",
    "## Templates (Databases & Services)",
    "",
    "```bash",
    "hoist template list",
    "hoist template info <name>",
    "hoist template create --type <type> [--version <v>] --server <s>  # --name defaults to --type",
    "hoist template services [--server <s>]",
    "hoist template inspect <name> [--server <s>]",
    "hoist template backup <name> [--server <s>] [--output <path>]",
    "hoist template destroy <name> [--server <s>] [--delete-volumes]",
    "hoist template stop <name> [--server <s>]",
    "hoist template start <name> [--server <s>]",
    "hoist template restart <name> [--server <s>]",
    "```",
    "",
    "Supported types: `postgres`, `mysql`, `mariadb`, `redis`, `mongodb`",
    "",
    "## Domains & SSL",
    "",
    "```bash",
    "hoist domain add <domain>                              # Auto-selects service if only one app",
    "hoist domain add <domain> --service <name>             # Auto-SSL via Caddy",
    "hoist domain list",
    "hoist domain delete <domain>",
    "```",
    "",
    "## Environment Variables",
    "",
    "```bash",
    "hoist env set <service> KEY=VAL KEY2=VAL2              # Server auto-resolved from hoist.json",
    "hoist env get <service> <key>",
    "hoist env list <service>                               # Returns real values in JSON mode",
    "hoist env delete <service> <key>",
    "hoist env import <service> .env",
    "hoist env export <service>",
    "```",
    "",
    "## Monitoring & Health",
    "",
    "```bash",
    "hoist logs <service> --lines 100",
    "hoist logs <service> --follow",
    "hoist status",
    "hoist doctor",
    "```",
    "",
    "## SSH Keys & Config",
    "",
    "```bash",
    "hoist keys show",
    "hoist keys rotate",
    "hoist config validate",
    "```",
    "",
    "## Utility",
    "",
    "```bash",
    "hoist --status                     # Quick overview: version, auth, providers",
    "npm install -g hoist-cli@latest    # Update to latest version",
    "```",
    "",
    "## Skill Export",
    "",
    "```bash",
    "hoist skill export --skill-version <version> [--name <name>] [-o <dir>]",
    "```",
    "",
  ].join("\n");
}

export function generateDockerfileReference(): string {
  return DOCKERFILES_MD;
}

function generateCodexSkill(): string {
  const lines: string[] = [
    "---",
    "name: managing-infrastructure",
    "description: Deploys and manages apps, servers, databases, domains, and environment variables on VPS providers using the Hoist CLI. Triggers when user mentions deploying, provisioning, databases, domains, env vars, or infrastructure health.",
    "---",
    "",
  ];

  lines.push(generateClaudeSkill().replace(/^---[\s\S]*?---\n\n/, ""));

  return lines.join("\n");
}

/** Writes skill files globally to all Agent Skills standard directories. */
export function writeAgentConfig(): string[] {
  const home = os.homedir();
  const written: string[] = [];

  const skillDirs = [
    { dir: path.join(home, ".claude", "skills", "hoist"), skill: generateClaudeSkill, label: "~/.claude" },
    { dir: path.join(home, ".cursor", "skills", "hoist"), skill: generateClaudeSkill, label: "~/.cursor" },
    { dir: path.join(home, ".gemini", "skills", "hoist"), skill: generateCodexSkill, label: "~/.gemini" },
    { dir: path.join(home, ".agents", "skills", "hoist"), skill: generateCodexSkill, label: "~/.agents" },
  ];

  for (const { dir, skill, label } of skillDirs) {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "SKILL.md"), skill(), "utf-8");
    fs.writeFileSync(path.join(dir, "COMMANDS.md"), generateCommandsReference(), "utf-8");
    fs.writeFileSync(path.join(dir, "DOCKERFILES.md"), generateDockerfileReference(), "utf-8");
    written.push(`${label}/skills/hoist/SKILL.md`);
    written.push(`${label}/skills/hoist/COMMANDS.md`);
    written.push(`${label}/skills/hoist/DOCKERFILES.md`);
  }

  return written;
}
