import fs from "node:fs";
import path from "node:path";
import os from "node:os";

import { DOCKERFILES_MD } from "./dockerfiles-reference.js";

export function generateSkillContent(): string {
  // Strip Claude-specific frontmatter, return just the body
  return generateClaudeSkill().replace(/^---[\s\S]*?---\n\n/, "");
}

export { generateCommandsReference };

function generateClaudeSkill(): string {
  return [
    "---",
    "name: managing-infrastructure",
    "description: Deploys and manages apps, servers, databases, domains, and environment variables on VPS providers (Hetzner, Vultr, DigitalOcean) using the Hoist CLI. Triggers when user mentions deploying, provisioning servers, creating databases, configuring domains, managing env vars, or checking infrastructure health.",
    "---",
    "",
    "# Hoist CLI",
    "",
    "## Auto-Detection",
    "",
    "When stdout is not a TTY (i.e., called from an agent), Hoist automatically:",
    "- Outputs JSON (no need for `--json`)",
    "- Skips confirmations (no need for `--yes`)",
    "- Auto-selects the only app service if just one exists",
    "- Auto-resolves `--server` from the service config in hoist.json",
    "- Generates random server names if `--name` is omitted",
    "- Uses cheapest server type and first region as defaults",
    "",
    "You can still pass `--json` and `--yes` explicitly if needed.",
    "",
    "## When to Use",
    "",
    '- "Deploy this app" -> `hoist deploy`',
    '- "Create a server" -> `hoist server create`',
    '- "Set up Postgres" -> `hoist template create --type postgres`',
    '- "Add a domain" -> `hoist domain add example.com`',
    '- "What\'s running?" -> `hoist status`',
    '- "Check health" -> `hoist doctor`',
    "",
    "## When NOT to Use",
    "",
    "- **Manual provider setup** (`hoist provider add`, `hoist provider update`) — always interactive, tell the user to run these.",
    "- **General coding** — Hoist is for infrastructure only.",
    "",
    "---",
    "",
    "## Decision Tree",
    "",
    "```",
    "Is hoist installed? (which hoist)",
    "+-- NO -> Run: npm install -g hoist-cli",
    "+--",
    "Is hoist configured? (hoist provider list)",
    "+-- NO -> Are HOIST_*_API_KEY env vars set?",
    "    +-- YES -> Run: hoist init (auto-configures from env vars)",
    "    +-- NO  -> Tell user to run: hoist init",
    "+-- YES -> Does hoist.json exist?",
    "    +-- NO -> Create hoist.json",
    "    +-- YES -> What does the user want?",
    "        +-- New server     -> hoist server create",
    "        +-- Import server  -> hoist server import --ip <ip>",
    "        +-- Deploy app     -> hoist deploy",
    "        +-- Add database   -> hoist template create --type postgres",
    "        +-- Add domain     -> hoist domain add <domain>",
    "        +-- Set env vars   -> hoist env set <service> KEY=VAL",
    "        +-- Check status   -> hoist status",
    "        +-- Diagnose issue -> hoist doctor",
    "```",
    "",
    "---",
    "",
    "## Sensitive Operations — Human in the Loop",
    "",
    "These commands prompt for API keys interactively — **only run them if env vars are set:**",
    "",
    "| Command | Behavior |",
    "|---------|----------|",
    "| `hoist init` | If `HOIST_*_API_KEY` env vars are set, auto-configures. Otherwise prompts for API keys (human only). |",
    "| `hoist provider add` | Always interactive — tell user to run this |",
    "| `hoist provider update <label>` | Always interactive — tell user to run this |",
    "| `hoist keys rotate` | Confirm key rotation on all servers (supports `--yes`) |",
    "",
    "Environment variables: `HOIST_HETZNER_API_KEY`, `HOIST_VULTR_API_KEY`, `HOIST_DIGITALOCEAN_API_KEY`",
    "",
    "When env vars are set, `hoist init --json` is fully autonomous — no prompts, no human needed.",
    "",
    "---",
    "",
    "## Commands",
    "",
    "For full command reference with all flags, see [COMMANDS.md](COMMANDS.md).",
    "",
    "**Providers:** `provider list`, `provider test`, `provider set-default`, `provider delete`",
    "",
    "**Servers:** `server create`, `server import`, `server list`, `server status <name>`, `server ssh <name>`, `server destroy <name>`",
    "",
    "**Deploy:** `deploy`, `deploy --service <name>`, `deploy --repo <url> --branch <branch>`, `rollback --service <name>`",
    "",
    "**Templates:** `template list`, `template info <name>`, `template create --type <type>`, `template services`, `template inspect <name>`, `template backup <name>`, `template destroy <name>`, `template stop/start/restart <name>`",
    "",
    "**Domains:** `domain add <domain> --service <name>`, `domain list`, `domain delete <domain>`",
    "",
    "**Env vars:** `env set <service> KEY=VAL`, `env get <service> <key>`, `env list <service>`, `env delete <service> <key>`, `env import <service> <file>`, `env export <service>`",
    "",
    "**Monitoring:** `logs <service>`, `logs <service> --follow`, `status`, `doctor`",
    "",
    "**Other:** `keys show`, `keys rotate`, `config validate`, `update`, `skill export`, `--status` (quick overview)",
    "",
    "JSON output and confirmation skipping are automatic when called from an agent (non-TTY). You can still pass `--json` and `--yes` explicitly if needed.",
    "",
    "---",
    "",
    "## Project Config",
    "",
    "Read `hoist.json` in the project root for current project context (servers, services, domains).",
    "",
    "```json",
    "{",
    '  "project": "my-app",',
    '  "servers": { "prod": { "provider": "hetzner-1" } },',
    '  "services": {',
    '    "api": { "server": "prod", "type": "app", "source": ".", "port": 3000 },',
    '    "db": { "server": "prod", "type": "postgres", "version": "16" }',
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Interactive Deployment Procedure",
    "",
    "Ask the user for each parameter before proceeding:",
    "",
    "1. **Server** — Which server? If none exist, ask: provider, region, type, name",
    "2. **Service** — App (needs Dockerfile + port) or database (pick type + version)? If no Dockerfile exists, generate one — see [DOCKERFILES.md](DOCKERFILES.md) for framework-specific examples.",
    "3. **Domain** (optional) — User must point DNS A record to server IP first",
    "4. **Env vars** (optional) — DATABASE_URL, API keys, etc.",
    "",
    "---",
    "",
    "## After Deploying",
    "",
    "1. `hoist status --json` — verify deployment",
    "2. `hoist domain add <domain> --service <name> --json` — custom domain + auto-SSL",
    "3. `hoist doctor --json` — health check",
    "",
    "## After Adding a Database",
    "",
    "1. `hoist template inspect <name> --json` — get credentials",
    "2. `hoist env set <app> DATABASE_URL=<url> --json` — inject into app",
    "",
    "## After an Error",
    "",
    "1. `hoist doctor --json` — diagnose",
    "2. `hoist logs <service> --lines 200 --json` — check logs",
    "3. `hoist rollback --service <name> --json --yes` — revert bad deploy",
    "",
    "---",
    "",
    "## Error Reference",
    "",
    "| Error | Solution |",
    "|-------|----------|",
    '| "Run hoist init first" | If env vars are set, run `hoist init --json`. Otherwise tell user to run `hoist init`. |',
    '| "Provider not found" | Check `hoist provider list` for correct label |',
    '| "Server not found" | Check `hoist server list --json` |',
    '| "SSH connection failed" | Run `hoist doctor --json`, verify IP |',
    '| "No hoist.json found" | Create hoist.json in project root |',
    '| "references unknown server" | Server name in service must match servers section |',
    "",
    "---",
    "",
    "## Golden Rules",
    "",
    "1. Just run commands — JSON output and confirmations are handled automatically when called from an agent",
    "2. Never handle API keys directly — use env vars (`HOIST_*_API_KEY`) or tell user to run setup commands",
    "3. Parse stdout for JSON, check exit code (0 = ok, 1 = error)",
    "4. Run `hoist doctor` to diagnose any issue",
    "5. Server names in hoist.json must match what was used during creation",
    "",
  ].join("\n");
}

function generateCommandsReference(): string {
  return [
    "# Hoist CLI — Full Command Reference",
    "",
    "All commands auto-detect non-TTY and output JSON + skip confirmations automatically. You can still pass `--json` and `--yes` explicitly if needed.",
    "",
    "## Init",
    "",
    "```bash",
    "hoist init                                # Auto-detects HOIST_*_API_KEY env vars, falls back to interactive",
    "```",
    "",
    "If any of these env vars are set, init auto-configures the provider (no prompts):",
    "- `HOIST_HETZNER_API_KEY`",
    "- `HOIST_VULTR_API_KEY`",
    "- `HOIST_DIGITALOCEAN_API_KEY`",
    "",
    "## Providers",
    "",
    "```bash",
    "hoist provider list",
    "hoist provider test [label]",
    "hoist provider set-default [label]",
    "hoist provider delete [label]",
    "```",
    "",
    "## Servers",
    "",
    "```bash",
    "hoist server create                                    # Auto: random name, cheapest type, first region",
    "hoist server create --name <n> --provider <p> --type <t> --region <r>  # Explicit",
    "hoist server import --ip <ip>                          # Auto: random name",
    "hoist server import --name <n> --ip <ip> [--user <user>]",
    "hoist server list [--provider <p>]",
    "hoist server status <name> [--provider <p>]",
    "hoist server ssh <name> [--provider <p>]",
    "hoist server destroy <name> [--provider <p>]",
    "```",
    "",
    "## Deploy & Rollback",
    "",
    "```bash",
    "hoist deploy                                           # Auto-selects service if only one app",
    "hoist deploy --service <name>                          # Deploy a specific service",
    "hoist deploy --repo <url> [--branch <branch>]          # From Git repo",
    "hoist rollback --service <name>                        # Server auto-resolved from hoist.json",
    "```",
    "",
    "## Templates (Databases & Services)",
    "",
    "```bash",
    "hoist template list",
    "hoist template info <name>",
    "hoist template create --type <type> [--version <v>] --server <s>  # --name defaults to --type",
    "hoist template services [--server <s>]",
    "hoist template inspect <name> [--server <s>]",
    "hoist template backup <name> [--server <s>] [--output <path>]",
    "hoist template destroy <name> [--server <s>] [--delete-volumes]",
    "hoist template stop <name> [--server <s>]",
    "hoist template start <name> [--server <s>]",
    "hoist template restart <name> [--server <s>]",
    "```",
    "",
    "Supported types: `postgres`, `mysql`, `mariadb`, `redis`, `mongodb`",
    "",
    "## Domains & SSL",
    "",
    "```bash",
    "hoist domain add <domain>                              # Auto-selects service if only one app",
    "hoist domain add <domain> --service <name>             # Auto-SSL via Caddy",
    "hoist domain list",
    "hoist domain delete <domain>",
    "```",
    "",
    "## Environment Variables",
    "",
    "```bash",
    "hoist env set <service> KEY=VAL KEY2=VAL2              # Server auto-resolved from hoist.json",
    "hoist env get <service> <key>",
    "hoist env list <service>                               # Returns real values in JSON mode",
    "hoist env delete <service> <key>",
    "hoist env import <service> .env",
    "hoist env export <service>",
    "```",
    "",
    "## Monitoring & Health",
    "",
    "```bash",
    "hoist logs <service> --lines 100",
    "hoist logs <service> --follow",
    "hoist status",
    "hoist doctor",
    "```",
    "",
    "## SSH Keys & Config",
    "",
    "```bash",
    "hoist keys show",
    "hoist keys rotate",
    "hoist config validate",
    "```",
    "",
    "## Update",
    "",
    "```bash",
    "hoist update                       # Update agent skill files + check for CLI updates",
    "hoist --status                     # Quick overview: version, auth, providers",
    "```",
    "",
    "## Skill Export",
    "",
    "```bash",
    "hoist skill export --skill-version <version> [--name <name>] [-o <dir>]",
    "```",
    "",
  ].join("\n");
}

export function generateDockerfileReference(): string {
  return DOCKERFILES_MD;
}

function generateCodexSkill(): string {
  const lines: string[] = [
    "---",
    "name: managing-infrastructure",
    "description: Deploys and manages apps, servers, databases, domains, and environment variables on VPS providers using the Hoist CLI. Triggers when user mentions deploying, provisioning, databases, domains, env vars, or infrastructure health.",
    "---",
    "",
  ];

  lines.push(generateClaudeSkill().replace(/^---[\s\S]*?---\n\n/, ""));

  return lines.join("\n");
}

/** Writes skill files globally to all Agent Skills standard directories. */
export function writeAgentConfig(): string[] {
  const home = os.homedir();
  const written: string[] = [];

  const skillDirs = [
    { dir: path.join(home, ".claude", "skills", "hoist"), skill: generateClaudeSkill, label: "~/.claude" },
    { dir: path.join(home, ".cursor", "skills", "hoist"), skill: generateClaudeSkill, label: "~/.cursor" },
    { dir: path.join(home, ".gemini", "skills", "hoist"), skill: generateCodexSkill, label: "~/.gemini" },
    { dir: path.join(home, ".agents", "skills", "hoist"), skill: generateCodexSkill, label: "~/.agents" },
  ];

  for (const { dir, skill, label } of skillDirs) {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "SKILL.md"), skill(), "utf-8");
    fs.writeFileSync(path.join(dir, "COMMANDS.md"), generateCommandsReference(), "utf-8");
    fs.writeFileSync(path.join(dir, "DOCKERFILES.md"), generateDockerfileReference(), "utf-8");
    written.push(`${label}/skills/hoist/SKILL.md`);
    written.push(`${label}/skills/hoist/COMMANDS.md`);
    written.push(`${label}/skills/hoist/DOCKERFILES.md`);
  }

  return written;
}
